# Generated by Django 5.1.3 on 2025-01-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_delete_cheese_delete_delights_delete_popsicles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='heading',
            field=models.CharField(default='pop', max_length=25),
        ),
    ]
