# Generated by Django 5.1.3 on 2025-01-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_cheese_delights_popsicles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='delights',
        ),
    ]
