# Generated by Django 5.1.3 on 2025-02-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_remove_product_discription_remove_product_library_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
