# Generated by Django 5.1.3 on 2025-01-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cheese',
        ),
        migrations.DeleteModel(
            name='delights',
        ),
        migrations.DeleteModel(
            name='popsicles',
        ),
        migrations.RemoveField(
            model_name='list',
            name='link_slug',
        ),
    ]
